CREATE TABLE "SUB_DETAIL" ( "SUB_ID" NUMBER(6,0), 
	"SUB_NM" VARCHAR2(100),
	"SEM" NUMBER(1,0) NOT NULL ENABLE,
	CONSTRAINT "SUB_DETAIL_PK" PRIMARY KEY ("SUB_ID")ENABLE) 
/
CREATE TABLE "SEM_BATCH" ("BATCH_ID" VARCHAR(5),
	"SEM" NUMBER (1,0),
	"BATCH" CHAR(1),
	CONSTRAINT "SEM_BATCH_PK" PRIMARY KEY ("BATCH_ID") ENABLE)
/
CREATE TABLE "STUDENT_DETAIL" ( "STD_ID" NUMBER(13,0), 
	"BC_ID" NUMBER(10,0), 
	"BATCH_ID" VARCHAR(5),
	CONSTRAINT "STUDENT_DETAIL_PK" PRIMARY KEY ("STD_ID") ENABLE,
	CONSTRAINT "STUDENT_DETAIL_FK1" FOREIGN KEY ("BATCH_ID") REFERENCES "SEM_BATCH" ("BATCH_ID") ENABLE)
/
CREATE TABLE "SLOT_MAP"("DAY" CHAR(3),
	"TIME" VARCHAR2(10),
	"SLOT_ID" NUMBER(5,0),
	CONSTRAINT "SLOT_MAP" PRIMARY KEY ("SLOT_ID") ENABLE)
/
CREATE TABLE "BATCH_WKDAY" ("ID" NUMBER(10) NOT NULL, 
	"BATCH_ID" VARCHAR(5),
	"SUB_ID" NUMBER(6,0),
  	"DAT" DATE,
	CONSTRAINT "BATCH_WKDAY_PK" PRIMARY KEY ("ID") ENABLE, 
	CONSTRAINT "BATCH_WKdDAY_FK1" FOREIGN KEY ("BATCH_ID") REFERENCES "SEM_BATCH" ("BATCH_ID") ENABLE,
	CONSTRAINT "BATCH_WKDAY_FK2" FOREIGN KEY ("SUB_ID") REFERENCES "SUB_DETAIL" ("SUB_ID") ENABLE) 
/
CREATE TABLE "LAB_TT" ("LAB_NM" VARCHAR2(25),
	"SLOT_ID"NUMBER(5,0),	
	"SUB_ID" NUMBER(6,0), 
	"BATCH_ID" VARCHAR(5),
	CONSTRAINT "LAB_TT_F1_PK" PRIMARY KEY ("SLOT_ID","LAB_NM") ENABLE, 
	CONSTRAINT "LAB_TT_FK1" FOREIGN KEY ("SUB_ID") REFERENCES "SUB_DETAIL" ("SUB_ID") ENABLE,
	CONSTRAINT "LAB_TT_FK2" FOREIGN KEY ("SLOT_ID") REFERENCES "SLOT_MAP" ("SLOT_ID") ENABLE , 
	CONSTRAINT "LAB_TT_FK3" FOREIGN KEY ("BATCH_ID") REFERENCES "SEM_BATCH" ("BATCH_ID") ENABLE)	
/
CREATE TABLE "ATTENDANCE" ("ID" NUMBER(10,0),
	"STD_ID" NUMBER(13,0),
	"SUB_ID" NUMBER(6,0),
	"DAT" DATE,
	CONSTRAINT "ATTENDANCE_PK" PRIMARY KEY ("ID") ENABLE,
	CONSTRAINT "ATTENDANCE_FK1" FOREIGN KEY ("STD_ID") REFERENCES "STUDENT_DETAIL" ("STD_ID") ENABLE,
	CONSTRAINT "ATTENDANCE_FK2" FOREIGN KEY ("SUB_ID") REFERENCES "SUB_DETAIL" ("SUB_ID") ENABLE)
/
CREATE TABLE "CLIENT" ("IP" VARCHAR2(20),
	"LAB_NM" VARCHAR2(3),
	"PRIORITY" NUMBER(20,0),
	CONSTRAINT "CLIENT_PK" PRIMARY KEY ("IP") ENABLE)
/

create sequence idp_id_seq_BATCH_WKDAY start with 1 increment by 1
/

CREATE SEQUENCE IDP_ID_SEQ_ATTENDANCE START WITH 1 INCREMENT BY 1
/

create or replace trigger idp_insert1
before insert on BATCH_WKDAY
for each row
begin
    select idp_id_seq_batch_wkday.nextval into :new.id from dual;
end;
/
create or replace trigger idp_insert2
before insert on ATTENDANCE
for each row
begin
    select idp_id_seq_attendance.nextval into :new.id from dual;
end;
/